version: '2'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes_from:
      - phpfpm:ro
    volumes:
      - ./docker/nginx/sites.conf:/etc/nginx/conf.d/default.conf:ro

  phpfpm:
    build: docker/phpfpm
    volumes:
      - ./:/var/www/homework:cached
    working_dir: /var/www/homework

  mysql:
    image: mariadb:10.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=homework
    volumes:
      - data:/var/lib/mysql:cached

volumes:
  data:
    driver: local
